# Goals:
- ### Saving work with Git
- ### Practice basic python commands

***

### Reminders:
- WiFi: TUGuest, should prompt you to accept terms and conditions in your favorite web browser
- 'Pull' the latest class materials
    - Navigate to your project folder in __Git Bash__ (for Windows) or __Terminal__ (for Mac + Linux) using the `cd` command
    - Enter `git pull` command to pull the latest version of the repo
- Activate your environment at the beginning of workshop:
    - Windows: `activate tds`
    - Linux, MacOS: `source activate tds`
- Start Jupyter with command `jupyter notebook`
- #### Ask Questions and help your neighbor!
    
*** 

### Intro to Python - Resources:
- https://learnpython.org/ 
- Python: https://docs.python.org/3/tutorial
- Codecademy (free + paid): https://www.codecademy.com/
- YouTube (personal preference):
    - Derek Banas:
        - Python Overview Video: https://www.youtube.com/watch?v=N4mEzFDjqtA
        - Python Playlist: https://www.youtube.com/watch?v=nwjAHQERL08&list=PLGLfVvz_LVvTn3cK5e6LjhgGiSeVlIRwt
    - Sentdex (More advanced, but still very useful): https://www.youtube.com/user/sentdex/playlists
- Stack Overflow (Especially useful for troubleshooting): https://stackoverflow.com/questions/tagged/python?sort=frequent&pageSize=15
- (If you know of others that you have found useful, let me know!)

***

## Saving Work with Git
#### Note: everything in this chunk takes place in the Git bash/terminal

In collaborative settings, Git is used to maintain *Version Control*, which is a way to keep track of multiple changes to multiple scripts by multiple people in __one__ project. 

One way to do so is by *creating copies* of the project through *branches*. Branches allow for separate tracking versions of the project, to be re-combined later. 

To create a new branch, type in your terminal:
> `git checkout -b <Whatever_you_want_to_call_your_branch>`

- The *checkout* command changes your working version of the project
- The *-b* option means to create a new branch, with the name you give it (in place of `<Whatever_you_want_to_call_your_branch>`)

To view your changes 
> `git status`

To save your work:
> `git add .`

> `git commit -m "<A message to describe your changes>"`

***
*Can have as many branches as you want, please break it!*

***

## Practice Basic Python Commands

In [8]:
print(74827 + 1000)
print(10 * 300)
print(300/20)
print(3**2)
7%2

75827
3000
15.0
9


1

In [11]:
x = 678
y  = 521
z=123

In [12]:
x+y

1199

## Data Types

In [21]:
print(type('aasdfasd'))
print(type(1))
print(type(1.))
print(type(print))
print(type(type))
print(type(x))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'builtin_function_or_method'>
<class 'type'>
<class 'int'>


# Arrays

In [33]:
import numpy as np
from numpy import array
data = [1,1,2,3,5,8]
print(data)

[1, 1, 2, 3, 5, 8]


In [34]:
#print(type(data))
data = array(data)
print(type(data))

<class 'numpy.ndarray'>


In [46]:
data = array([1,2,3,4,5,6])
print(data)

[1 2 3 4 5 6]


In [48]:
data = array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


### Indexing

In [42]:
data[2]

2

In [43]:
print(len(data))

6


In [39]:
print(data[len(data)-1])

8


In [49]:
data[0]

array([1, 2])

In [50]:
data[0][1]

2

# Slicing

In [64]:
dataset = array([0,1,2,3,4,5,6,7,8,9])
print(dataset)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
dataset[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [55]:
twodataset = array([[1,2,3],[4,5,6],[7,8,9]])
print(twodataset)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
twodataset[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [72]:
strings = array(['a','b',1])

In [73]:
strings[2]

'1'

In [74]:
print(dataset)

[0 1 2 3 4 5 6 7 8 9]


In [75]:
print(dataset[3:])

[3 4 5 6 7 8 9]


In [76]:
print(twodataset)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
print([twodataset[i,i] for i in range(3)])

[1, 5, 9]


In [87]:
[i*2 for i in range(5)]

[0, 2, 4, 6, 8]

In [94]:
[i+2 for i in range(5)]

[2, 3, 4, 5, 6]

In [90]:
list(range(5))

[0, 1, 2, 3, 4]

In [91]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |