# Intro to NN Math
Lecture video: https://youtu.be/rfmi8rLg1P8

### Resources:
- Neural Network in 11 Lines of Code: https://iamtrask.github.io/2015/07/12/basic-python-network/
- Playground.tensorflow (Visual Neural network): https://playground.tensorflow.org/
- 3B1B - Useful Neural Network YouTube videos: https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi 

In [2]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

# input dataset
X = np.array([
[0,0,1],
[0,1,1],
[1,0,1],
[1,1,1],
])
 
# output dataset           
y = np.array([[0,0,1,1]]).T

In [3]:
##y

In [4]:
##print(y)

In [10]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [11]:
##print (syn0)

In [12]:
for iter in range(10000):
 
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)
#     if iter % 1000 == 0:
#         print(iter,"\n",syn0)

In [20]:
test = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1],[0,1,0]])

##print("output expecting 0,0,1,1")
##print (nonlin(np.dot(test,syn0)))
##print ("no Sigmoid","\n",(np.dot(test,syn0))) 

no Sigmoid 
 [[-4.62963669]
 [-4.83748019]
 [ 5.04335634]
 [ 4.83551284]
 [-0.2078435 ]]


In [21]:
##print (np.round((nonlin(np.dot(test,syn0))),0))

In [14]:
print ("Output After Training:")
print (l1)

Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]


In [15]:
# print(np.round(l1,0))

[[0.]
 [0.]
 [1.]
 [1.]]
